# Generated by Django 4.1 on 2022-12-27 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('street1', models.TextField()),
                ('street2', models.TextField()),
                ('street3', models.TextField()),
                ('city', models.TextField()),
                ('locationId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('createdTime', models.TimeField(auto_now=True)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mvc')),
            ],
        ),
    ]
