# Generated by Django 4.1 on 2022-12-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_mvc_street3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvc',
            name='street2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
