# Generated by Django 4.1 on 2022-12-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221226_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
