# Generated by Django 4.1 on 2022-12-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_record_createdtime_alter_record_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarliestByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliestTime', models.DateTimeField()),
                ('day', models.DateField(auto_now_add=True)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mvc')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliableNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('locationId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.mvc')),
            ],
        ),
    ]
