# Generated by Django 4.1 on 2022-12-30 19:23

from django.db import migrations
import requests

def init_data(apps, schema_editor):
    # We can't import the MVC model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    MVC = apps.get_model('api', 'MVC')
    for mvc in MVC.objects.all():
        street1=mvc.street1
        street2=mvc.street2
        city=mvc.city
        if street2:
            address = street1+', '+street2+', '+city+', NJ, USA'
        else:
            address=street1+', '+city+', NJ, USA'
        address.replace(' ','%20')
        url = 'https://maps.googleapis.com/maps/api/geocode/json?address='+address+'&key=MY_API_ADDRESS'
        response = requests.get(url).json()['results']
        if len(response)>0:
            response=response[0]['geometry']['location']
            mvc.lat=response['lat']
            mvc.long=response['lng']
            mvc.save()
        else:
            print(mvc.name)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mvc_lat_mvc_long'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
