# Generated by Django 4.1 on 2023-01-05 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221230_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('day', models.DateField()),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mvc')),
            ],
        ),
    ]
